### ISSUE TITLE
vagrantのバージョン

### ISSUE THREAD

**Issue by y-teraz** [shirasagi/ss-vagrant#12]
ご検証の上で、マニュアルの更新をお願いしたいです。

環境構築済で、virtualboxの方だけv6.0へUPしていた状態で、シラサギを起動しようとしたところ、vagrantが起動しませんでした。
vagrant v2.2.0からv2.2.5へUPしたところ、シラサギの起動ができました。

### 環境
Mac
virtualbox v6.0
vagrant 2.2.0→2.2.5

### vagrant更新前のメッセージ
`$ vagrant resume
==> vagrant: A new version of Vagrant is available: 2.2.5 (installed version: 2.2.0)!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.
`

**Comment by itowtips** [comment]
#13 
README.md を修正しました。
windows を検証中です。

**Comment by itowtips** [comment]
windows を検証して、README.md を更新しました。

~~~
virtualbox v6.0.12
vagrant 2.2.5
~~~
